SAST Fail example

diff --git a/.github/workflows/mainCICD.yml b/.github/workflows/mainCICD.yml
--- a/.github/workflows/mainCICD.yml
+++ b/.github/workflows/mainCICD.yml
@@ -64,10 +64,10 @@ jobs:
 
       # Alleen tijdelijk gebruiken als je wilt aantonen dat de SAST-job kan falen.
       # Daarna weer verwijderen.
-      # - name: Fail SAST test intentionally
-      #   run: |
-      #     echo "SAST test failed intentionally for demonstration"
-      #     exit 1
+      - name: Fail SAST test intentionally
+        run: |
+          echo "SAST test failed intentionally for demonstration"
+          exit 1
 
   sca:
     name: SCA - Dependency Review
